apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1
  labels:
    app: nginx
    type: front-end
spec:
  containers:
    - name: nginx
      image: mohankrish3/nginx:tagVersion
      ports:
        - containerPort: 8080
