apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1
  labels:
    app: nginx
    type: front-end
spec:
  containers:
    - name: nginx
      image: mohankrish3/nginxkube:tagVersion
      ports:
        - containerPort: 80
      #imagePullSecrets:
      # - name: registry-secret
